baseURL = 'blog.minseong.xyz'
languageCode = 'ko-kr'
title = "Magic(physics) tool, which could resolve any bugs"
theme = "vanilla"
buildFuture = true
paginate = 5
permalinks = [
  { post = "/:2006/:01/:02/:filename" }
]
params = [
  shortTitle = "Blog"
  contact = "mscho@ubuntu-kr.org"
  github = "kkumtree"
  launchpad = "mscho7969"
  source_repo = "https://github.com/kkumtree/blog.minseong.xyz"
  defaultContentLanguage = "ko"
