name: Deploy Website
on:
  push:
    branches: [ main ]

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Check out latest commit 
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        name: Checkout src repo
        with:
          ref: main

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: 'themes/v-framework/package-lock.json'

      - name: Install Dart Sass
        run: npm install -g sass

      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.163.3'
          extended: true
          
      - name: Install theme dependencies  
        working-directory: 'themes/v-framework'
        run: npm ci --no-audit --no-fund
         
      - name: Build website with hugo
        run: hugo --minify

      # Checkout destination branch
      - uses: actions/checkout@v4
        name: Checkout dest repo
        with:
          path: dest
          fetch-depth: 0
          ref: gh-pages
            
      # Commit and push changes
      - name: Copy website built from src/public
        working-directory: dest
        run: |
          rm -rf ./*
          rsync -a --delete ../public/ ./

      # Commit and push changes
      - name: Commit website updates
        working-directory: dest
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "Deploy website updates with GitHub Actions: ${GITHUB_SHA}"
          git push origin gh-pages
